//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.AlumnoMateriaCalificacions = new HashSet<AlumnoMateriaCalificacion>();
            this.ProfesorMaterias = new HashSet<ProfesorMateria>();
        }
    
        public int IdProfesor { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public Nullable<int> IdRol { get; set; }
    
        public virtual ICollection<AlumnoMateriaCalificacion> AlumnoMateriaCalificacions { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<ProfesorMateria> ProfesorMaterias { get; set; }
    }
}
