//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Alumnos = new HashSet<Alumno>();
            this.Profesors = new HashSet<Profesor>();
        }
    
        public int IdRol { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Alumno> Alumnos { get; set; }
        public virtual ICollection<Profesor> Profesors { get; set; }
    }
}
